#!/usr/bin/env python3
"""Build, audit, and generate phrase-sized TTS clips for Fleshpunk."""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
EVENTS_PATH = ROOT / "events.json"
SYMBIOTES_PATH = ROOT / "symbiotes.json"
FOLLOWUPS_PATH = ROOT / "audio" / "tts_followups.json"
MANIFEST_PATH = ROOT / "audio" / "tts_manifest.json"
OUTPUT_DIR = ROOT / "audio" / "tts"
CACHE_PATH = OUTPUT_DIR / ".tts_cache.json"

DEFAULT_MODEL = "gpt-4o-mini-tts"
DEFAULT_VOICE = "nova"
DEFAULT_RESPONSE_FORMAT = "wav"
DEFAULT_INSTRUCTIONS = (
    "Low, controlled field report. Clipped phrasing. Natural pacing. "
    "No theatrical delivery. Do not overperform horror."
)

NUMBER_WORDS = [
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
]

SYSTEM_CLIPS = [
    ("system_unknown_command", "I did not match that."),
    ("system_repeat_prompt", "Say repeat choices, status, or a choice number."),
    ("system_status_header", "Status report."),
    ("system_inventory_header", "Inventory report."),
    ("system_confirm", "Confirm that action."),
    ("system_cancelled", "Action cancelled."),
    ("system_paused", "Audio paused."),
    ("system_continue", "Audio continuing."),
    ("system_choices_header", "Current choices."),
    ("system_no_legal_action", "No legal action matched."),
    ("system_generation_notice", "This voice is generated by artificial intelligence."),
]


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    return value or "clip"


def normalize_tts_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"([.!?]){2,}", r"\1", text)
    if text and text[-1] not in ".!?":
        text += "."
    return text


def phrase_fragment(text: str) -> str:
    return re.sub(r"[.!?]+$", "", re.sub(r"\s+", " ", text).strip())


def clip_hash(clip: dict[str, Any]) -> str:
    payload = {
        "text": clip.get("text", ""),
        "model": clip.get("model", DEFAULT_MODEL),
        "voice": clip.get("voice", DEFAULT_VOICE),
        "instructions": clip.get("instructions", DEFAULT_INSTRUCTIONS),
        "response_format": clip.get("response_format", DEFAULT_RESPONSE_FORMAT),
    }
    raw = json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def make_clip(clip_id: str, text: str, category: str, source: str) -> dict[str, Any]:
    clip_id = slugify(clip_id)
    filename = f"{clip_id}.{DEFAULT_RESPONSE_FORMAT}"
    return {
        "id": clip_id,
        "category": category,
        "source": source,
        "text": normalize_tts_text(text),
        "text_key": text_key(text),
        "model": DEFAULT_MODEL,
        "voice": DEFAULT_VOICE,
        "instructions": DEFAULT_INSTRUCTIONS,
        "response_format": DEFAULT_RESPONSE_FORMAT,
        "file": f"res://audio/tts/{filename}",
    }


def text_key(text: str) -> str:
    return hashlib.sha256(normalize_tts_text(text).casefold().encode("utf-8")).hexdigest()


def iter_events(events_payload: dict[str, Any]) -> list[tuple[str, str, dict[str, Any]]]:
    events: list[tuple[str, str, dict[str, Any]]] = []
    for room_id, room_events in events_payload.get("room_events", {}).items():
        if not isinstance(room_events, list):
            continue
        for event in room_events:
            if isinstance(event, dict):
                events.append((str(room_id), str(event.get("id", "unknown")), event))
    for event_id, event in events_payload.get("special_events", {}).items():
        if isinstance(event, dict):
            events.append(("special_events", str(event_id), event))
    return events


def index_symbiotes() -> dict[str, dict[str, Any]]:
    payload = read_json(SYMBIOTES_PATH)
    symbiotes: dict[str, dict[str, Any]] = {}
    for symbiote in payload.get("symbiotes", []):
        if isinstance(symbiote, dict):
            symbiote_id = str(symbiote.get("id", ""))
            if symbiote_id:
                symbiotes[symbiote_id] = symbiote
    return symbiotes


def runtime_buttons_for_event(event: dict[str, Any], symbiotes: dict[str, dict[str, Any]]) -> list[dict[str, str]]:
    buttons: list[dict[str, str]] = []
    symbiote_choices = event.get("symbiote_choices", [])
    if isinstance(symbiote_choices, list) and symbiote_choices:
        for symbiote_id_variant in symbiote_choices:
            symbiote_id = str(symbiote_id_variant)
            symbiote = symbiotes.get(symbiote_id, {})
            if not symbiote:
                continue
            buttons.append({
                "label": symbiote_bond_label(symbiote_id, symbiote),
                "action": "take_symbiote:%s" % symbiote_id,
            })

    raw_buttons = event.get("buttons", [])
    if isinstance(raw_buttons, list):
        for button in raw_buttons:
            if isinstance(button, dict):
                buttons.append({
                    "label": str(button.get("label", "")),
                    "action": str(button.get("action", "")),
                })

    if not buttons:
        buttons.append({"label": "Proceed", "action": "proceed"})
    return buttons


def symbiote_bond_label(symbiote_id: str, symbiote: dict[str, Any]) -> str:
    name = str(symbiote.get("name", symbiote_id))
    if symbiote_id == "impermeable_barrier":
        return f"Bond: {name}, armor shield"
    if symbiote_id == "pheromones":
        return f"Bond: {name}, weaken enemies"
    if symbiote_id == "mitosis_unit":
        return f"Bond: {name}, one death save"
    return f"Bond: {name}"


def followup_phrases() -> list[str]:
    if not FOLLOWUPS_PATH.exists():
        return []
    payload = read_json(FOLLOWUPS_PATH)
    phrases: list[str] = []
    for phrase in payload.get("phrases", []):
        phrase_text = normalize_tts_text(str(phrase))
        if phrase_text and phrase_text not in phrases:
            phrases.append(phrase_text)
    return phrases


def stat_phrases() -> list[str]:
    phrases: list[str] = []

    def add(text: str) -> None:
        phrase_text = normalize_tts_text(text)
        if phrase_text not in phrases:
            phrases.append(phrase_text)

    for value in range(0, 121):
        add(f"Biomass: {value}.")
        add(f"Biomass now {value}.")
        add(f"I only have {value}.")
        add(f"It wants {value} biomass.")

    for value in range(0, 41):
        add(f"Corruption: {value}.")
        add(f"Corruption now {value}.")
        add(f"Corruption rises to {value}.")
        add(f"Corruption settles to {value}.")
        add(f"Danger: {value}.")
        add(f"Danger now {value}.")
        add(f"Danger rises to {value}.")
        add(f"Danger settles to {value}.")
        add(f"Claim: {value}.")
        add(f"Claim now {value}.")
        add(f"Marked route streak: {value}.")
        add(f"Enemy tier {value}.")
        add(f"Health restored: {value}.")
        add(f"Shield restored: {value}.")
        add(f"{value} damage hit.")
        add(f"Damage hit {value}.")
        add(f"Barrier blocked {value}.")
        add(f"Armor blocked {value}.")
        add(f"Shield lost {value}.")
        add(f"Health lost {value}.")
        add(f"The pool knits {value} health back into place.")
        add(f"The amber hardens over me and restores {value} shield.")
        add(f"The soft tunnel carries me forward and mends {value} health.")

    for mutation_name, mutation_cost in (
        ("Lean Muscle", 6),
        ("Bigger Scythe", 8),
        ("Spring Sinew", 7),
        ("Bone Plates", 7),
        ("Spiked Armor", 9),
    ):
        add(f"The scale wants {mutation_cost} biomass for {mutation_name}.")

    return phrases


def build_manifest() -> dict[str, Any]:
    events_payload = read_json(EVENTS_PATH)
    symbiotes = index_symbiotes()
    clips: list[dict[str, Any]] = []

    for clip_id, text in SYSTEM_CLIPS:
        clips.append(make_clip(clip_id, text, "system", "system"))

    for room_id, event_id, event in iter_events(events_payload):
        source = f"{room_id}.{event_id}"
        for line_key in ("line_1", "line_2"):
            text = event.get(line_key)
            if isinstance(text, str) and text.strip():
                clips.append(make_clip(f"{event_id}_{line_key}", text, "narration", f"{source}.{line_key}"))

        for index, button in enumerate(runtime_buttons_for_event(event, symbiotes)):
            label = str(button.get("label", "")).strip()
            if not label:
                continue
            number = NUMBER_WORDS[index] if index < len(NUMBER_WORDS) else str(index + 1)
            clips.append(
                make_clip(
                    f"{event_id}_choice_{index + 1}",
                    f"Choice {number}. {phrase_fragment(label)}.",
                    "choice",
                    f"{source}.buttons[{index}]",
                )
            )

    for phrase in followup_phrases():
        digest = text_key(phrase)[:12]
        clips.append(make_clip(f"followup_{digest}", phrase, "followup", "audio/tts_followups.json"))

    for phrase in stat_phrases():
        digest = text_key(phrase)[:12]
        clips.append(make_clip(f"stat_{digest}", phrase, "stat", "generated stat phrase"))

    seen: dict[str, int] = {}
    deduped: list[dict[str, Any]] = []
    for clip in clips:
        base_id = str(clip["id"])
        count = seen.get(base_id, 0)
        seen[base_id] = count + 1
        if count:
            clip["id"] = f"{base_id}_{count + 1}"
            suffix = f"_{count + 1}.{clip['response_format']}"
            clip["file"] = str(clip["file"]).replace(f".{clip['response_format']}", suffix)
        clip["hash"] = clip_hash(clip)
        deduped.append(clip)

    return {
        "version": 1,
        "generated_at": dt.datetime.now(dt.UTC).isoformat(),
        "source_events": "res://events.json",
        "default_model": DEFAULT_MODEL,
        "default_voice": DEFAULT_VOICE,
        "default_response_format": DEFAULT_RESPONSE_FORMAT,
        "default_instructions": DEFAULT_INSTRUCTIONS,
        "clips": deduped,
    }


def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"missing manifest: {path}")
    payload = read_json(path)
    if not isinstance(payload, dict):
        raise ValueError("manifest root must be an object")
    return payload


def res_to_path(res_path: str) -> Path:
    if not res_path.startswith("res://"):
        raise ValueError(f"file must use res:// path: {res_path}")
    return ROOT / res_path.removeprefix("res://")


def audit_manifest(payload: dict[str, Any]) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    clips = payload.get("clips")
    if not isinstance(clips, list):
        return [{"severity": "high", "location": "clips", "issue": "clips must be a list"}]

    seen_ids: set[str] = set()
    seen_files: set[str] = set()
    for index, clip in enumerate(clips):
        location = f"clips[{index}]"
        if not isinstance(clip, dict):
            findings.append({"severity": "high", "location": location, "issue": "clip must be an object"})
            continue

        clip_id = str(clip.get("id", "")).strip()
        text = str(clip.get("text", "")).strip()
        file_path = str(clip.get("file", "")).strip()
        response_format = str(clip.get("response_format", DEFAULT_RESPONSE_FORMAT)).strip()

        if not clip_id:
            findings.append({"severity": "high", "location": location, "issue": "missing id"})
        elif clip_id in seen_ids:
            findings.append({"severity": "high", "location": location, "issue": f"duplicate id: {clip_id}"})
        seen_ids.add(clip_id)

        if not text:
            findings.append({"severity": "high", "location": location, "issue": "missing text"})
        elif len(text.split()) < 2:
            findings.append({"severity": "high", "location": location, "issue": "single-word clip; use a phrase"})
        elif len(text) > 700:
            findings.append({"severity": "medium", "location": location, "issue": "clip text is long; split it"})
        if re.search(r"[.!?]{2,}", text):
            findings.append({"severity": "medium", "location": location, "issue": "repeated punctuation in TTS text"})

        if not file_path.startswith("res://audio/tts/"):
            findings.append({"severity": "high", "location": location, "issue": "file must be under res://audio/tts/"})
        elif file_path in seen_files:
            findings.append({"severity": "high", "location": location, "issue": f"duplicate file: {file_path}"})
        seen_files.add(file_path)

        if response_format not in {"mp3", "opus", "aac", "flac", "wav", "pcm"}:
            findings.append({"severity": "high", "location": location, "issue": f"unsupported response_format: {response_format}"})

    return findings


def load_cache() -> dict[str, Any]:
    if not CACHE_PATH.exists():
        return {}
    try:
        payload = read_json(CACHE_PATH)
    except json.JSONDecodeError:
        return {}
    return payload if isinstance(payload, dict) else {}


def save_cache(cache: dict[str, Any]) -> None:
    write_json(CACHE_PATH, cache)


def create_speech(clip: dict[str, Any], api_key: str) -> bytes:
    body = {
        "model": clip.get("model", DEFAULT_MODEL),
        "voice": clip.get("voice", DEFAULT_VOICE),
        "input": clip["text"],
        "instructions": clip.get("instructions", DEFAULT_INSTRUCTIONS),
        "response_format": clip.get("response_format", DEFAULT_RESPONSE_FORMAT),
    }
    raw_body = json.dumps(body).encode("utf-8")
    request = urllib.request.Request(
        "https://api.openai.com/v1/audio/speech",
        data=raw_body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            return response.read()
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenAI speech request failed: {exc.code} {detail}") from exc


def normalize_wav_header(audio: bytes) -> bytes:
    if len(audio) < 44 or audio[:4] != b"RIFF" or audio[8:12] != b"WAVE":
        return audio

    patched = bytearray(audio)
    patched[4:8] = (len(audio) - 8).to_bytes(4, "little")
    data_index = audio.find(b"data")
    if data_index != -1 and data_index + 8 <= len(audio):
        data_size = len(audio) - data_index - 8
        patched[data_index + 4:data_index + 8] = data_size.to_bytes(4, "little")
    return bytes(patched)


def write_mock_wav(path: Path) -> None:
    # A tiny valid silent WAV lets the pipeline prove file paths without spending API calls.
    sample_rate = 8000
    data = b"\x00\x00" * 800
    byte_rate = sample_rate * 2
    block_align = 2
    bits_per_sample = 16
    riff_size = 36 + len(data)
    header = (
        b"RIFF"
        + riff_size.to_bytes(4, "little")
        + b"WAVEfmt "
        + (16).to_bytes(4, "little")
        + (1).to_bytes(2, "little")
        + (1).to_bytes(2, "little")
        + sample_rate.to_bytes(4, "little")
        + byte_rate.to_bytes(4, "little")
        + block_align.to_bytes(2, "little")
        + bits_per_sample.to_bytes(2, "little")
        + b"data"
        + len(data).to_bytes(4, "little")
    )
    path.write_bytes(header + data)


def cmd_refresh(args: argparse.Namespace) -> int:
    manifest = build_manifest()
    out = Path(args.out) if args.out else MANIFEST_PATH
    if not out.is_absolute():
        out = ROOT / out
    if args.check:
        existing = load_manifest(out)
        expected = dict(manifest)
        current = dict(existing)
        expected.pop("generated_at", None)
        current.pop("generated_at", None)
        if expected != current:
            print("manifest is stale", file=sys.stderr)
            return 1
        print("ok")
        return 0
    write_json(out, manifest)
    print(out)
    return 0


def cmd_audit(args: argparse.Namespace) -> int:
    manifest = load_manifest(Path(args.manifest) if args.manifest else MANIFEST_PATH)
    findings = audit_manifest(manifest)
    if args.json:
        print(json.dumps({"findings": findings}, indent=2, ensure_ascii=False))
    elif findings:
        for finding in findings:
            print("{severity}: {location}: {issue}".format(**finding))
    else:
        print("ok")
    return 1 if findings and args.fail_on_findings else 0


def cmd_plan(args: argparse.Namespace) -> int:
    manifest = load_manifest(Path(args.manifest) if args.manifest else MANIFEST_PATH)
    cache = load_cache()
    rows = []
    for clip in manifest.get("clips", []):
        if not isinstance(clip, dict):
            continue
        digest = clip_hash(clip)
        output = res_to_path(str(clip.get("file", "")))
        cached = cache.get(str(clip.get("id")), {}).get("hash") == digest
        rows.append({
            "id": clip.get("id"),
            "category": clip.get("category"),
            "exists": output.exists(),
            "cached": cached,
            "file": clip.get("file"),
        })
    print(json.dumps({"clips": rows}, indent=2, ensure_ascii=False))
    return 0


def cmd_generate(args: argparse.Namespace) -> int:
    manifest = load_manifest(Path(args.manifest) if args.manifest else MANIFEST_PATH)
    findings = audit_manifest(manifest)
    if findings:
        for finding in findings:
            print("{severity}: {location}: {issue}".format(**finding), file=sys.stderr)
        return 1

    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key and not args.mock:
        print("OPENAI_API_KEY is required unless --mock is used", file=sys.stderr)
        return 1

    clips = [clip for clip in manifest.get("clips", []) if isinstance(clip, dict)]
    if args.category:
        clips = [clip for clip in clips if clip.get("category") == args.category]
    if args.prefix:
        clips = [clip for clip in clips if str(clip.get("id", "")).startswith(args.prefix)]
    if args.clip_id:
        requested_ids = set(args.clip_id)
        clips = [clip for clip in clips if str(clip.get("id", "")) in requested_ids]
    if args.limit:
        clips = clips[: args.limit]

    cache = load_cache()
    generated = 0
    skipped = 0
    for clip in clips:
        clip_id = str(clip["id"])
        digest = clip_hash(clip)
        output = res_to_path(str(clip["file"]))
        output.parent.mkdir(parents=True, exist_ok=True)
        cached = cache.get(clip_id, {}).get("hash") == digest
        if output.exists() and cached and not args.force:
            skipped += 1
            continue
        if args.mock:
            write_mock_wav(output)
        else:
            audio = create_speech(clip, api_key)
            if str(clip.get("response_format", DEFAULT_RESPONSE_FORMAT)) == "wav":
                audio = normalize_wav_header(audio)
            output.write_bytes(audio)
        cache[clip_id] = {
            "hash": digest,
            "file": clip["file"],
            "generated_at": dt.datetime.now(dt.UTC).isoformat(),
            "mock": bool(args.mock),
        }
        generated += 1
        print(f"generated {clip_id} -> {clip['file']}")

    save_cache(cache)
    print(f"done: generated={generated} skipped={skipped}")
    return 0


def cmd_embed(args: argparse.Namespace) -> int:
    manifest = load_manifest(Path(args.manifest) if args.manifest else MANIFEST_PATH)
    lookup = {}
    for clip in manifest.get("clips", []):
        if not isinstance(clip, dict):
            continue
        path = res_to_path(str(clip.get("file", "")))
        if not path.exists():
            continue
        lookup[str(clip.get("id"))] = {
            "mime": f"audio/{clip.get('response_format', DEFAULT_RESPONSE_FORMAT)}",
            "base64": base64.b64encode(path.read_bytes()).decode("ascii"),
        }
    print(json.dumps({"clips": lookup}, indent=2, ensure_ascii=False))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build and generate phrase-sized TTS clips.")
    sub = parser.add_subparsers(dest="command", required=True)

    refresh = sub.add_parser("refresh", help="Rebuild audio/tts_manifest.json from events.json.")
    refresh.add_argument("--out", help="Manifest output path.")
    refresh.add_argument("--check", action="store_true", help="Fail if the manifest is stale.")
    refresh.set_defaults(func=cmd_refresh)

    audit = sub.add_parser("audit", help="Audit the TTS manifest.")
    audit.add_argument("--manifest", help="Manifest path.")
    audit.add_argument("--json", action="store_true", help="Print JSON findings.")
    audit.add_argument("--fail-on-findings", action="store_true", help="Exit nonzero when findings are present.")
    audit.set_defaults(func=cmd_audit)

    plan = sub.add_parser("plan", help="Show which clips exist and are cache-current.")
    plan.add_argument("--manifest", help="Manifest path.")
    plan.set_defaults(func=cmd_plan)

    generate = sub.add_parser("generate", help="Generate missing or stale clips.")
    generate.add_argument("--manifest", help="Manifest path.")
    generate.add_argument("--category", help="Only generate clips from one category.")
    generate.add_argument("--prefix", help="Only generate clips whose id starts with this prefix.")
    generate.add_argument("--clip-id", action="append", help="Generate one specific clip id. May be repeated.")
    generate.add_argument("--limit", type=int, help="Only process the first N matching clips.")
    generate.add_argument("--force", action="store_true", help="Regenerate clips even when cache-current.")
    generate.add_argument("--mock", action="store_true", help="Write tiny silent WAV files instead of calling OpenAI.")
    generate.set_defaults(func=cmd_generate)

    embed = sub.add_parser("embed", help="Print existing generated clips as base64 JSON.")
    embed.add_argument("--manifest", help="Manifest path.")
    embed.set_defaults(func=cmd_embed)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        return args.func(args)
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
